"""initial migration

Revision ID: ef6657ece334
Revises: 
Create Date: 2025-09-15 11:44:05.259149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef6657ece334'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('annotations_property_id_fkey'), 'annotations', type_='foreignkey')
    op.create_foreign_key(None, 'annotations', 'properties', ['property_id'], ['id'], ondelete='CASCADE')
    op.alter_column('property_snapshots', 'parking',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('property_snapshots', 'elevator',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('property_snapshots', 'new_construction',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('property_snapshots', 'rented',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('property_snapshots', 'trespasse',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.create_index(op.f('ix_property_snapshots_address'), 'property_snapshots', ['address'], unique=False)
    op.create_index(op.f('ix_property_snapshots_agency'), 'property_snapshots', ['agency'], unique=False)
    op.create_index(op.f('ix_property_snapshots_city'), 'property_snapshots', ['city'], unique=False)
    op.create_index(op.f('ix_property_snapshots_district'), 'property_snapshots', ['district'], unique=False)
    op.create_index(op.f('ix_property_snapshots_tags'), 'property_snapshots', ['tags'], unique=False)
    op.create_index(op.f('ix_property_snapshots_typology'), 'property_snapshots', ['typology'], unique=False)
    op.create_index(op.f('ix_property_snapshots_zone'), 'property_snapshots', ['zone'], unique=False)
    op.drop_constraint(op.f('property_snapshots_snapshot_id_fkey'), 'property_snapshots', type_='foreignkey')
    op.drop_constraint(op.f('property_snapshots_property_id_fkey'), 'property_snapshots', type_='foreignkey')
    op.create_foreign_key(None, 'property_snapshots', 'properties', ['property_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'property_snapshots', 'snapshots', ['snapshot_id'], ['id'], ondelete='CASCADE')
    op.drop_column('property_snapshots', 'image_url')
    op.drop_column('property_snapshots', 'video_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property_snapshots', sa.Column('video_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('property_snapshots', sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'property_snapshots', type_='foreignkey')
    op.drop_constraint(None, 'property_snapshots', type_='foreignkey')
    op.create_foreign_key(op.f('property_snapshots_property_id_fkey'), 'property_snapshots', 'properties', ['property_id'], ['id'])
    op.create_foreign_key(op.f('property_snapshots_snapshot_id_fkey'), 'property_snapshots', 'snapshots', ['snapshot_id'], ['id'])
    op.drop_index(op.f('ix_property_snapshots_zone'), table_name='property_snapshots')
    op.drop_index(op.f('ix_property_snapshots_typology'), table_name='property_snapshots')
    op.drop_index(op.f('ix_property_snapshots_tags'), table_name='property_snapshots')
    op.drop_index(op.f('ix_property_snapshots_district'), table_name='property_snapshots')
    op.drop_index(op.f('ix_property_snapshots_city'), table_name='property_snapshots')
    op.drop_index(op.f('ix_property_snapshots_agency'), table_name='property_snapshots')
    op.drop_index(op.f('ix_property_snapshots_address'), table_name='property_snapshots')
    op.alter_column('property_snapshots', 'trespasse',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('property_snapshots', 'rented',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('property_snapshots', 'new_construction',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('property_snapshots', 'elevator',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('property_snapshots', 'parking',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.drop_constraint(None, 'annotations', type_='foreignkey')
    op.create_foreign_key(op.f('annotations_property_id_fkey'), 'annotations', 'properties', ['property_id'], ['id'])
    # ### end Alembic commands ###
