"""add image_url and video_url back

Revision ID: f5eec541e497
Revises: ef6657ece334
Create Date: 2025-09-15 11:48:05.989408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5eec541e497'
down_revision: Union[str, Sequence[str], None] = 'ef6657ece334'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('annotations_property_id_fkey'), 'annotations', type_='foreignkey')
    op.create_foreign_key(None, 'annotations', 'properties', ['property_id'], ['id'])
    op.drop_column('annotations', 'interesting')
    op.add_column('property_snapshots', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('property_snapshots', sa.Column('video_url', sa.String(), nullable=True))
    op.drop_constraint(op.f('property_snapshots_property_id_fkey'), 'property_snapshots', type_='foreignkey')
    op.drop_constraint(op.f('property_snapshots_snapshot_id_fkey'), 'property_snapshots', type_='foreignkey')
    op.create_foreign_key(None, 'property_snapshots', 'properties', ['property_id'], ['id'])
    op.create_foreign_key(None, 'property_snapshots', 'snapshots', ['snapshot_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'property_snapshots', type_='foreignkey')
    op.drop_constraint(None, 'property_snapshots', type_='foreignkey')
    op.create_foreign_key(op.f('property_snapshots_snapshot_id_fkey'), 'property_snapshots', 'snapshots', ['snapshot_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('property_snapshots_property_id_fkey'), 'property_snapshots', 'properties', ['property_id'], ['id'], ondelete='CASCADE')
    op.drop_column('property_snapshots', 'video_url')
    op.drop_column('property_snapshots', 'image_url')
    op.add_column('annotations', sa.Column('interesting', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'annotations', type_='foreignkey')
    op.create_foreign_key(op.f('annotations_property_id_fkey'), 'annotations', 'properties', ['property_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
